### ISSUE TITLE
What's the difference between `cp` and `sync -n` ?

### ISSUE THREAD

**Issue by balthild** [wchang22/LuminS#16]

**Comment by wchang22** [comment]
Let's say we have source directory A which contains file x and destination directory B which contains file y.
Let's say x and y are the exact same file.

`lms cp` is simply a multithreaded version of regular `cp -r`, where all files in A are copied over to B. This means y in B will be overwritten with the contents of x in A, even though x and y are the same file.

`lms sync -n` synchronizes B with A, but does not delete any files in B that are not in A, and does not copy any files that are in both A and B. This means that because x and y are the same, y will be left untouched.

**Comment by balthild** [comment]
Thanks!
